// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#undef _HAS_EXCEPTIONS

#include "messages.h"

#include <flutter/basic_message_channel.h>
#include <flutter/binary_messenger.h>
#include <flutter/encodable_value.h>
#include <flutter/standard_message_codec.h>

#include <cmath>
#include <limits>
#include <map>
#include <optional>
#include <string>

namespace flutter_print {
using ::flutter::BasicMessageChannel;
using ::flutter::CustomEncodableValue;
using ::flutter::EncodableList;
using ::flutter::EncodableMap;
using ::flutter::EncodableValue;

FlutterError CreateConnectionError(const std::string channel_name) {
  return FlutterError(
      "channel-error",
      "Unable to establish connection on channel: '" + channel_name + "'.",
      EncodableValue(""));
}

namespace {
template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b);

bool PigeonInternalDeepEquals(const double& a, const double& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b);

template<typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b);

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b);

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b);

template<typename T>
bool PigeonInternalDeepEquals(const T& a, const T& b) {
  return a == b;
}

template<typename T>
bool PigeonInternalDeepEquals(const std::vector<T>& a, const std::vector<T>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (size_t i = 0; i < a.size(); ++i) {
    if (!PigeonInternalDeepEquals(a[i], b[i])) {
      return false;
    }
  }
  return true;
}

template <typename K, typename V>
bool PigeonInternalDeepEquals(const std::map<K, V>& a, const std::map<K, V>& b) {
  if (a.size() != b.size()) {
    return false;
  }
  for (const auto& kv : a) {
    bool found = false;
    for (const auto& b_kv : b) {
      if (PigeonInternalDeepEquals(kv.first, b_kv.first)) {
        if (PigeonInternalDeepEquals(kv.second, b_kv.second)) {
          found = true;
          break;
        } else {
          return false;
        }
      }
    }
    if (!found) {
      return false;
    }
  }
  return true;
}

bool PigeonInternalDeepEquals(const double& a, const double& b) {
  // Normalize -0.0 to 0.0 and handle NaN equality.
  return (a == b) || (std::isnan(a) && std::isnan(b));
}

template<typename T>
bool PigeonInternalDeepEquals(const std::optional<T>& a, const std::optional<T>& b) {
  if (!a && !b) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

template<typename T>
bool PigeonInternalDeepEquals(const std::unique_ptr<T>& a, const std::unique_ptr<T>& b) {
  if (a.get() == b.get()) {
    return true;
  }
  if (!a || !b) {
    return false;
  }
  return PigeonInternalDeepEquals(*a, *b);
}

bool PigeonInternalDeepEquals(const ::flutter::EncodableValue& a, const ::flutter::EncodableValue& b) {
  if (a.index() != b.index()) {
    return false;
  }
  if (const double* da = std::get_if<double>(&a)) {
    return PigeonInternalDeepEquals(*da, std::get<double>(b));
  } else if (const ::flutter::EncodableList* la = std::get_if<::flutter::EncodableList>(&a)) {
    return PigeonInternalDeepEquals(*la, std::get<::flutter::EncodableList>(b));
  } else if (const ::flutter::EncodableMap* ma = std::get_if<::flutter::EncodableMap>(&a)) {
    return PigeonInternalDeepEquals(*ma, std::get<::flutter::EncodableMap>(b));
  }
  return a == b;
}

template <typename T>
size_t PigeonInternalDeepHash(const T& v);

size_t PigeonInternalDeepHash(const double& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v);

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v);

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v);

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v);

template <typename T>
size_t PigeonInternalDeepHash(const T& v) {
  return std::hash<T>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::vector<T>& v) {
  size_t result = 1;
  for (const auto& item : v) {
    result = result * 31 + PigeonInternalDeepHash(item);
  }
  return result;
}

template <typename K, typename V>
size_t PigeonInternalDeepHash(const std::map<K, V>& v) {
  size_t result = 0;
  for (const auto& kv : v) {
    result += ((PigeonInternalDeepHash(kv.first) * 31) ^ PigeonInternalDeepHash(kv.second));
  }
  return result;
}

size_t PigeonInternalDeepHash(const double& v) {
  if (std::isnan(v)) {
    // Normalize NaN to a consistent hash.
    return std::hash<double>()(std::numeric_limits<double>::quiet_NaN());
  }
  if (v == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return std::hash<double>()(0.0);
  }
  return std::hash<double>()(v);
}

template <typename T>
size_t PigeonInternalDeepHash(const std::optional<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

template <typename T>
size_t PigeonInternalDeepHash(const std::unique_ptr<T>& v) {
  return v ? PigeonInternalDeepHash(*v) : 0;
}

size_t PigeonInternalDeepHash(const ::flutter::EncodableValue& v) {
  size_t result = v.index();
  if (const double* dv = std::get_if<double>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*dv);
  } else if (const ::flutter::EncodableList* lv =
                 std::get_if<::flutter::EncodableList>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*lv);
  } else if (const ::flutter::EncodableMap* mv =
                 std::get_if<::flutter::EncodableMap>(&v)) {
    result = result * 31 + PigeonInternalDeepHash(*mv);
  } else {
    std::visit(
        [&result](const auto& val) {
          using T = std::decay_t<decltype(val)>;
          if constexpr (!std::is_same_v<T, double> &&
                        !std::is_same_v<T, ::flutter::EncodableList> &&
                        !std::is_same_v<T, ::flutter::EncodableMap> &&
                        !std::is_same_v<T, std::monostate> &&
                        !std::is_same_v<T, ::flutter::CustomEncodableValue>) {
            result = result * 31 + PigeonInternalDeepHash(val);
          }
        },
        v);
  }
  return result;
}

}  // namespace
// PageSize

PageSize::PageSize(const std::string& name)
 : name_(name) {}

PageSize::PageSize(
  const std::string& name,
  const double* width,
  const double* height)
 : name_(name),
    width_(width ? std::optional<double>(*width) : std::nullopt),
    height_(height ? std::optional<double>(*height) : std::nullopt) {}

const std::string& PageSize::name() const {
  return name_;
}

void PageSize::set_name(std::string_view value_arg) {
  name_ = value_arg;
}


const double* PageSize::width() const {
  return width_ ? &(*width_) : nullptr;
}

void PageSize::set_width(const double* value_arg) {
  width_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void PageSize::set_width(double value_arg) {
  width_ = value_arg;
}


const double* PageSize::height() const {
  return height_ ? &(*height_) : nullptr;
}

void PageSize::set_height(const double* value_arg) {
  height_ = value_arg ? std::optional<double>(*value_arg) : std::nullopt;
}

void PageSize::set_height(double value_arg) {
  height_ = value_arg;
}


EncodableList PageSize::ToEncodableList() const {
  EncodableList list;
  list.reserve(3);
  list.push_back(EncodableValue(name_));
  list.push_back(width_ ? EncodableValue(*width_) : EncodableValue());
  list.push_back(height_ ? EncodableValue(*height_) : EncodableValue());
  return list;
}

PageSize PageSize::FromEncodableList(const EncodableList& list) {
  PageSize decoded(
    std::get<std::string>(list[0]));
  auto& encodable_width = list[1];
  if (!encodable_width.IsNull()) {
    decoded.set_width(std::get<double>(encodable_width));
  }
  auto& encodable_height = list[2];
  if (!encodable_height.IsNull()) {
    decoded.set_height(std::get<double>(encodable_height));
  }
  return decoded;
}

bool PageSize::operator==(const PageSize& other) const {
  return PigeonInternalDeepEquals(name_, other.name_) && PigeonInternalDeepEquals(width_, other.width_) && PigeonInternalDeepEquals(height_, other.height_);
}

bool PageSize::operator!=(const PageSize& other) const {
  return !(*this == other);
}

size_t PageSize::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(name_);
  result = result * 31 + PigeonInternalDeepHash(width_);
  result = result * 31 + PigeonInternalDeepHash(height_);
  return result;
}

size_t PigeonInternalDeepHash(const PageSize& v) {
  return v.Hash();
}

// PageMargins

PageMargins::PageMargins(
  double top,
  double bottom,
  double left,
  double right)
 : top_(top),
    bottom_(bottom),
    left_(left),
    right_(right) {}

double PageMargins::top() const {
  return top_;
}

void PageMargins::set_top(double value_arg) {
  top_ = value_arg;
}


double PageMargins::bottom() const {
  return bottom_;
}

void PageMargins::set_bottom(double value_arg) {
  bottom_ = value_arg;
}


double PageMargins::left() const {
  return left_;
}

void PageMargins::set_left(double value_arg) {
  left_ = value_arg;
}


double PageMargins::right() const {
  return right_;
}

void PageMargins::set_right(double value_arg) {
  right_ = value_arg;
}


EncodableList PageMargins::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(EncodableValue(top_));
  list.push_back(EncodableValue(bottom_));
  list.push_back(EncodableValue(left_));
  list.push_back(EncodableValue(right_));
  return list;
}

PageMargins PageMargins::FromEncodableList(const EncodableList& list) {
  PageMargins decoded(
    std::get<double>(list[0]),
    std::get<double>(list[1]),
    std::get<double>(list[2]),
    std::get<double>(list[3]));
  return decoded;
}

bool PageMargins::operator==(const PageMargins& other) const {
  return PigeonInternalDeepEquals(top_, other.top_) && PigeonInternalDeepEquals(bottom_, other.bottom_) && PigeonInternalDeepEquals(left_, other.left_) && PigeonInternalDeepEquals(right_, other.right_);
}

bool PageMargins::operator!=(const PageMargins& other) const {
  return !(*this == other);
}

size_t PageMargins::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(top_);
  result = result * 31 + PigeonInternalDeepHash(bottom_);
  result = result * 31 + PigeonInternalDeepHash(left_);
  result = result * 31 + PigeonInternalDeepHash(right_);
  return result;
}

size_t PigeonInternalDeepHash(const PageMargins& v) {
  return v.Hash();
}

// PrintOptions

PrintOptions::PrintOptions(
  int64_t copies,
  bool landscape,
  bool color)
 : copies_(copies),
    landscape_(landscape),
    color_(color) {}

PrintOptions::PrintOptions(
  const std::string* printer_address,
  const PageSize* page_size,
  const PageMargins* margins,
  int64_t copies,
  bool landscape,
  bool color,
  const DuplexMode* duplex_mode)
 : printer_address_(printer_address ? std::optional<std::string>(*printer_address) : std::nullopt),
    page_size_(page_size ? std::make_unique<PageSize>(*page_size) : nullptr),
    margins_(margins ? std::make_unique<PageMargins>(*margins) : nullptr),
    copies_(copies),
    landscape_(landscape),
    color_(color),
    duplex_mode_(duplex_mode ? std::optional<DuplexMode>(*duplex_mode) : std::nullopt) {}

PrintOptions::PrintOptions(const PrintOptions& other)
 : printer_address_(other.printer_address_ ? std::optional<std::string>(*other.printer_address_) : std::nullopt),
    page_size_(other.page_size_ ? std::make_unique<PageSize>(*other.page_size_) : nullptr),
    margins_(other.margins_ ? std::make_unique<PageMargins>(*other.margins_) : nullptr),
    copies_(other.copies_),
    landscape_(other.landscape_),
    color_(other.color_),
    duplex_mode_(other.duplex_mode_ ? std::optional<DuplexMode>(*other.duplex_mode_) : std::nullopt) {}

PrintOptions& PrintOptions::operator=(const PrintOptions& other) {
  printer_address_ = other.printer_address_;
  page_size_ = other.page_size_ ? std::make_unique<PageSize>(*other.page_size_) : nullptr;
  margins_ = other.margins_ ? std::make_unique<PageMargins>(*other.margins_) : nullptr;
  copies_ = other.copies_;
  landscape_ = other.landscape_;
  color_ = other.color_;
  duplex_mode_ = other.duplex_mode_;
  return *this;
}

const std::string* PrintOptions::printer_address() const {
  return printer_address_ ? &(*printer_address_) : nullptr;
}

void PrintOptions::set_printer_address(const std::string_view* value_arg) {
  printer_address_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrintOptions::set_printer_address(std::string_view value_arg) {
  printer_address_ = value_arg;
}


const PageSize* PrintOptions::page_size() const {
  return page_size_.get();
}

void PrintOptions::set_page_size(const PageSize* value_arg) {
  page_size_ = value_arg ? std::make_unique<PageSize>(*value_arg) : nullptr;
}

void PrintOptions::set_page_size(const PageSize& value_arg) {
  page_size_ = std::make_unique<PageSize>(value_arg);
}


const PageMargins* PrintOptions::margins() const {
  return margins_.get();
}

void PrintOptions::set_margins(const PageMargins* value_arg) {
  margins_ = value_arg ? std::make_unique<PageMargins>(*value_arg) : nullptr;
}

void PrintOptions::set_margins(const PageMargins& value_arg) {
  margins_ = std::make_unique<PageMargins>(value_arg);
}


int64_t PrintOptions::copies() const {
  return copies_;
}

void PrintOptions::set_copies(int64_t value_arg) {
  copies_ = value_arg;
}


bool PrintOptions::landscape() const {
  return landscape_;
}

void PrintOptions::set_landscape(bool value_arg) {
  landscape_ = value_arg;
}


bool PrintOptions::color() const {
  return color_;
}

void PrintOptions::set_color(bool value_arg) {
  color_ = value_arg;
}


const DuplexMode* PrintOptions::duplex_mode() const {
  return duplex_mode_ ? &(*duplex_mode_) : nullptr;
}

void PrintOptions::set_duplex_mode(const DuplexMode* value_arg) {
  duplex_mode_ = value_arg ? std::optional<DuplexMode>(*value_arg) : std::nullopt;
}

void PrintOptions::set_duplex_mode(const DuplexMode& value_arg) {
  duplex_mode_ = value_arg;
}


EncodableList PrintOptions::ToEncodableList() const {
  EncodableList list;
  list.reserve(7);
  list.push_back(printer_address_ ? EncodableValue(*printer_address_) : EncodableValue());
  list.push_back(page_size_ ? CustomEncodableValue(*page_size_) : EncodableValue());
  list.push_back(margins_ ? CustomEncodableValue(*margins_) : EncodableValue());
  list.push_back(EncodableValue(copies_));
  list.push_back(EncodableValue(landscape_));
  list.push_back(EncodableValue(color_));
  list.push_back(duplex_mode_ ? CustomEncodableValue(*duplex_mode_) : EncodableValue());
  return list;
}

PrintOptions PrintOptions::FromEncodableList(const EncodableList& list) {
  PrintOptions decoded(
    std::get<int64_t>(list[3]),
    std::get<bool>(list[4]),
    std::get<bool>(list[5]));
  auto& encodable_printer_address = list[0];
  if (!encodable_printer_address.IsNull()) {
    decoded.set_printer_address(std::get<std::string>(encodable_printer_address));
  }
  auto& encodable_page_size = list[1];
  if (!encodable_page_size.IsNull()) {
    decoded.set_page_size(std::any_cast<const PageSize&>(std::get<CustomEncodableValue>(encodable_page_size)));
  }
  auto& encodable_margins = list[2];
  if (!encodable_margins.IsNull()) {
    decoded.set_margins(std::any_cast<const PageMargins&>(std::get<CustomEncodableValue>(encodable_margins)));
  }
  auto& encodable_duplex_mode = list[6];
  if (!encodable_duplex_mode.IsNull()) {
    decoded.set_duplex_mode(std::any_cast<const DuplexMode&>(std::get<CustomEncodableValue>(encodable_duplex_mode)));
  }
  return decoded;
}

bool PrintOptions::operator==(const PrintOptions& other) const {
  return PigeonInternalDeepEquals(printer_address_, other.printer_address_) && PigeonInternalDeepEquals(page_size_, other.page_size_) && PigeonInternalDeepEquals(margins_, other.margins_) && PigeonInternalDeepEquals(copies_, other.copies_) && PigeonInternalDeepEquals(landscape_, other.landscape_) && PigeonInternalDeepEquals(color_, other.color_) && PigeonInternalDeepEquals(duplex_mode_, other.duplex_mode_);
}

bool PrintOptions::operator!=(const PrintOptions& other) const {
  return !(*this == other);
}

size_t PrintOptions::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(printer_address_);
  result = result * 31 + PigeonInternalDeepHash(page_size_);
  result = result * 31 + PigeonInternalDeepHash(margins_);
  result = result * 31 + PigeonInternalDeepHash(copies_);
  result = result * 31 + PigeonInternalDeepHash(landscape_);
  result = result * 31 + PigeonInternalDeepHash(color_);
  result = result * 31 + PigeonInternalDeepHash(duplex_mode_);
  return result;
}

size_t PigeonInternalDeepHash(const PrintOptions& v) {
  return v.Hash();
}

// PrinterCapabilities

PrinterCapabilities::PrinterCapabilities(const EncodableList& supported_page_sizes)
 : supported_page_sizes_(supported_page_sizes) {}

PrinterCapabilities::PrinterCapabilities(
  const bool* supports_color,
  const bool* supports_duplex,
  const int64_t* max_copies,
  const EncodableList& supported_page_sizes)
 : supports_color_(supports_color ? std::optional<bool>(*supports_color) : std::nullopt),
    supports_duplex_(supports_duplex ? std::optional<bool>(*supports_duplex) : std::nullopt),
    max_copies_(max_copies ? std::optional<int64_t>(*max_copies) : std::nullopt),
    supported_page_sizes_(supported_page_sizes) {}

const bool* PrinterCapabilities::supports_color() const {
  return supports_color_ ? &(*supports_color_) : nullptr;
}

void PrinterCapabilities::set_supports_color(const bool* value_arg) {
  supports_color_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrinterCapabilities::set_supports_color(bool value_arg) {
  supports_color_ = value_arg;
}


const bool* PrinterCapabilities::supports_duplex() const {
  return supports_duplex_ ? &(*supports_duplex_) : nullptr;
}

void PrinterCapabilities::set_supports_duplex(const bool* value_arg) {
  supports_duplex_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrinterCapabilities::set_supports_duplex(bool value_arg) {
  supports_duplex_ = value_arg;
}


const int64_t* PrinterCapabilities::max_copies() const {
  return max_copies_ ? &(*max_copies_) : nullptr;
}

void PrinterCapabilities::set_max_copies(const int64_t* value_arg) {
  max_copies_ = value_arg ? std::optional<int64_t>(*value_arg) : std::nullopt;
}

void PrinterCapabilities::set_max_copies(int64_t value_arg) {
  max_copies_ = value_arg;
}


const EncodableList& PrinterCapabilities::supported_page_sizes() const {
  return supported_page_sizes_;
}

void PrinterCapabilities::set_supported_page_sizes(const EncodableList& value_arg) {
  supported_page_sizes_ = value_arg;
}


EncodableList PrinterCapabilities::ToEncodableList() const {
  EncodableList list;
  list.reserve(4);
  list.push_back(supports_color_ ? EncodableValue(*supports_color_) : EncodableValue());
  list.push_back(supports_duplex_ ? EncodableValue(*supports_duplex_) : EncodableValue());
  list.push_back(max_copies_ ? EncodableValue(*max_copies_) : EncodableValue());
  list.push_back(EncodableValue(supported_page_sizes_));
  return list;
}

PrinterCapabilities PrinterCapabilities::FromEncodableList(const EncodableList& list) {
  PrinterCapabilities decoded(
    std::get<EncodableList>(list[3]));
  auto& encodable_supports_color = list[0];
  if (!encodable_supports_color.IsNull()) {
    decoded.set_supports_color(std::get<bool>(encodable_supports_color));
  }
  auto& encodable_supports_duplex = list[1];
  if (!encodable_supports_duplex.IsNull()) {
    decoded.set_supports_duplex(std::get<bool>(encodable_supports_duplex));
  }
  auto& encodable_max_copies = list[2];
  if (!encodable_max_copies.IsNull()) {
    decoded.set_max_copies(std::get<int64_t>(encodable_max_copies));
  }
  return decoded;
}

bool PrinterCapabilities::operator==(const PrinterCapabilities& other) const {
  return PigeonInternalDeepEquals(supports_color_, other.supports_color_) && PigeonInternalDeepEquals(supports_duplex_, other.supports_duplex_) && PigeonInternalDeepEquals(max_copies_, other.max_copies_) && PigeonInternalDeepEquals(supported_page_sizes_, other.supported_page_sizes_);
}

bool PrinterCapabilities::operator!=(const PrinterCapabilities& other) const {
  return !(*this == other);
}

size_t PrinterCapabilities::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(supports_color_);
  result = result * 31 + PigeonInternalDeepHash(supports_duplex_);
  result = result * 31 + PigeonInternalDeepHash(max_copies_);
  result = result * 31 + PigeonInternalDeepHash(supported_page_sizes_);
  return result;
}

size_t PigeonInternalDeepHash(const PrinterCapabilities& v) {
  return v.Hash();
}

// PrinterInfo

PrinterInfo::PrinterInfo(
  const std::string& label,
  bool is_default,
  const PrinterCapabilities& capabilities)
 : label_(label),
    is_default_(is_default),
    capabilities_(std::make_unique<PrinterCapabilities>(capabilities)) {}

PrinterInfo::PrinterInfo(
  const std::string& label,
  const std::string* address,
  const std::string* description,
  bool is_default,
  const PrinterCapabilities& capabilities,
  const bool* is_available)
 : label_(label),
    address_(address ? std::optional<std::string>(*address) : std::nullopt),
    description_(description ? std::optional<std::string>(*description) : std::nullopt),
    is_default_(is_default),
    capabilities_(std::make_unique<PrinterCapabilities>(capabilities)),
    is_available_(is_available ? std::optional<bool>(*is_available) : std::nullopt) {}

PrinterInfo::PrinterInfo(const PrinterInfo& other)
 : label_(other.label_),
    address_(other.address_ ? std::optional<std::string>(*other.address_) : std::nullopt),
    description_(other.description_ ? std::optional<std::string>(*other.description_) : std::nullopt),
    is_default_(other.is_default_),
    capabilities_(std::make_unique<PrinterCapabilities>(*other.capabilities_)),
    is_available_(other.is_available_ ? std::optional<bool>(*other.is_available_) : std::nullopt) {}

PrinterInfo& PrinterInfo::operator=(const PrinterInfo& other) {
  label_ = other.label_;
  address_ = other.address_;
  description_ = other.description_;
  is_default_ = other.is_default_;
  capabilities_ = std::make_unique<PrinterCapabilities>(*other.capabilities_);
  is_available_ = other.is_available_;
  return *this;
}

const std::string& PrinterInfo::label() const {
  return label_;
}

void PrinterInfo::set_label(std::string_view value_arg) {
  label_ = value_arg;
}


const std::string* PrinterInfo::address() const {
  return address_ ? &(*address_) : nullptr;
}

void PrinterInfo::set_address(const std::string_view* value_arg) {
  address_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_address(std::string_view value_arg) {
  address_ = value_arg;
}


const std::string* PrinterInfo::description() const {
  return description_ ? &(*description_) : nullptr;
}

void PrinterInfo::set_description(const std::string_view* value_arg) {
  description_ = value_arg ? std::optional<std::string>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_description(std::string_view value_arg) {
  description_ = value_arg;
}


bool PrinterInfo::is_default() const {
  return is_default_;
}

void PrinterInfo::set_is_default(bool value_arg) {
  is_default_ = value_arg;
}


const PrinterCapabilities& PrinterInfo::capabilities() const {
  return *capabilities_;
}

void PrinterInfo::set_capabilities(const PrinterCapabilities& value_arg) {
  capabilities_ = std::make_unique<PrinterCapabilities>(value_arg);
}


const bool* PrinterInfo::is_available() const {
  return is_available_ ? &(*is_available_) : nullptr;
}

void PrinterInfo::set_is_available(const bool* value_arg) {
  is_available_ = value_arg ? std::optional<bool>(*value_arg) : std::nullopt;
}

void PrinterInfo::set_is_available(bool value_arg) {
  is_available_ = value_arg;
}


EncodableList PrinterInfo::ToEncodableList() const {
  EncodableList list;
  list.reserve(6);
  list.push_back(EncodableValue(label_));
  list.push_back(address_ ? EncodableValue(*address_) : EncodableValue());
  list.push_back(description_ ? EncodableValue(*description_) : EncodableValue());
  list.push_back(EncodableValue(is_default_));
  list.push_back(CustomEncodableValue(*capabilities_));
  list.push_back(is_available_ ? EncodableValue(*is_available_) : EncodableValue());
  return list;
}

PrinterInfo PrinterInfo::FromEncodableList(const EncodableList& list) {
  PrinterInfo decoded(
    std::get<std::string>(list[0]),
    std::get<bool>(list[3]),
    std::any_cast<const PrinterCapabilities&>(std::get<CustomEncodableValue>(list[4])));
  auto& encodable_address = list[1];
  if (!encodable_address.IsNull()) {
    decoded.set_address(std::get<std::string>(encodable_address));
  }
  auto& encodable_description = list[2];
  if (!encodable_description.IsNull()) {
    decoded.set_description(std::get<std::string>(encodable_description));
  }
  auto& encodable_is_available = list[5];
  if (!encodable_is_available.IsNull()) {
    decoded.set_is_available(std::get<bool>(encodable_is_available));
  }
  return decoded;
}

bool PrinterInfo::operator==(const PrinterInfo& other) const {
  return PigeonInternalDeepEquals(label_, other.label_) && PigeonInternalDeepEquals(address_, other.address_) && PigeonInternalDeepEquals(description_, other.description_) && PigeonInternalDeepEquals(is_default_, other.is_default_) && PigeonInternalDeepEquals(capabilities_, other.capabilities_) && PigeonInternalDeepEquals(is_available_, other.is_available_);
}

bool PrinterInfo::operator!=(const PrinterInfo& other) const {
  return !(*this == other);
}

size_t PrinterInfo::Hash() const {
  size_t result = 1;
  result = result * 31 + PigeonInternalDeepHash(label_);
  result = result * 31 + PigeonInternalDeepHash(address_);
  result = result * 31 + PigeonInternalDeepHash(description_);
  result = result * 31 + PigeonInternalDeepHash(is_default_);
  result = result * 31 + PigeonInternalDeepHash(capabilities_);
  result = result * 31 + PigeonInternalDeepHash(is_available_);
  return result;
}

size_t PigeonInternalDeepHash(const PrinterInfo& v) {
  return v.Hash();
}


PigeonInternalCodecSerializer::PigeonInternalCodecSerializer() {}

EncodableValue PigeonInternalCodecSerializer::ReadValueOfType(
  uint8_t type,
  ::flutter::ByteStreamReader* stream) const {
  switch (type) {
    case 129: {
        const auto& encodable_enum_arg = ReadValue(stream);
        const int64_t enum_arg_value = encodable_enum_arg.IsNull() ? 0 : encodable_enum_arg.LongValue();
        return encodable_enum_arg.IsNull() ? EncodableValue() : CustomEncodableValue(static_cast<DuplexMode>(enum_arg_value));
      }
    case 130: {
        return CustomEncodableValue(PageSize::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 131: {
        return CustomEncodableValue(PageMargins::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 132: {
        return CustomEncodableValue(PrintOptions::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 133: {
        return CustomEncodableValue(PrinterCapabilities::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    case 134: {
        return CustomEncodableValue(PrinterInfo::FromEncodableList(std::get<EncodableList>(ReadValue(stream))));
      }
    default:
      return ::flutter::StandardCodecSerializer::ReadValueOfType(type, stream);
    }
}

void PigeonInternalCodecSerializer::WriteValue(
  const EncodableValue& value,
  ::flutter::ByteStreamWriter* stream) const {
  if (const CustomEncodableValue* custom_value = std::get_if<CustomEncodableValue>(&value)) {
    if (custom_value->type() == typeid(DuplexMode)) {
      stream->WriteByte(129);
      WriteValue(EncodableValue(static_cast<int>(std::any_cast<DuplexMode>(*custom_value))), stream);
      return;
    }
    if (custom_value->type() == typeid(PageSize)) {
      stream->WriteByte(130);
      WriteValue(EncodableValue(std::any_cast<PageSize>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PageMargins)) {
      stream->WriteByte(131);
      WriteValue(EncodableValue(std::any_cast<PageMargins>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrintOptions)) {
      stream->WriteByte(132);
      WriteValue(EncodableValue(std::any_cast<PrintOptions>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrinterCapabilities)) {
      stream->WriteByte(133);
      WriteValue(EncodableValue(std::any_cast<PrinterCapabilities>(*custom_value).ToEncodableList()), stream);
      return;
    }
    if (custom_value->type() == typeid(PrinterInfo)) {
      stream->WriteByte(134);
      WriteValue(EncodableValue(std::any_cast<PrinterInfo>(*custom_value).ToEncodableList()), stream);
      return;
    }
  }
  ::flutter::StandardCodecSerializer::WriteValue(value, stream);
}

/// The codec used by FlutterPrintApi.
const ::flutter::StandardMessageCodec& FlutterPrintApi::GetCodec() {
  return ::flutter::StandardMessageCodec::GetInstance(&PigeonInternalCodecSerializer::GetInstance());
}

// Sets up an instance of `FlutterPrintApi` to handle messages through the `binary_messenger`.
void FlutterPrintApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  FlutterPrintApi* api) {
  FlutterPrintApi::SetUp(binary_messenger, api, "");
}

void FlutterPrintApi::SetUp(
  ::flutter::BinaryMessenger* binary_messenger,
  FlutterPrintApi* api,
  const std::string& message_channel_suffix) {
  const std::string prepended_suffix = message_channel_suffix.length() > 0 ? std::string(".") + message_channel_suffix : "";
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print.FlutterPrintApi.print" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_file_path_arg = args.at(0);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_options_arg = args.at(1);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const PrintOptions&>(std::get<CustomEncodableValue>(encodable_options_arg));
          std::optional<FlutterError> output = api->Print(file_path_arg, options_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print.FlutterPrintApi.printPreview" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          const auto& args = std::get<EncodableList>(message);
          const auto& encodable_file_path_arg = args.at(0);
          if (encodable_file_path_arg.IsNull()) {
            reply(WrapError("file_path_arg unexpectedly null."));
            return;
          }
          const auto& file_path_arg = std::get<std::string>(encodable_file_path_arg);
          const auto& encodable_options_arg = args.at(1);
          if (encodable_options_arg.IsNull()) {
            reply(WrapError("options_arg unexpectedly null."));
            return;
          }
          const auto& options_arg = std::any_cast<const PrintOptions&>(std::get<CustomEncodableValue>(encodable_options_arg));
          std::optional<FlutterError> output = api->PrintPreview(file_path_arg, options_arg);
          if (output.has_value()) {
            reply(WrapError(output.value()));
            return;
          }
          EncodableList wrapped;
          wrapped.push_back(EncodableValue());
          reply(EncodableValue(std::move(wrapped)));
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print.FlutterPrintApi.listPrinters" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->ListPrinters([reply](ErrorOr<EncodableList>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            wrapped.push_back(EncodableValue(std::move(output).TakeValue()));
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
  {
    BasicMessageChannel<> channel(binary_messenger, "dev.flutter.pigeon.flutter_print.FlutterPrintApi.pickPrinter" + prepended_suffix, &GetCodec());
    if (api != nullptr) {
      channel.SetMessageHandler([api](const EncodableValue& message, const ::flutter::MessageReply<EncodableValue>& reply) {
        try {
          api->PickPrinter([reply](ErrorOr<std::optional<PrinterInfo>>&& output) {
            if (output.has_error()) {
              reply(WrapError(output.error()));
              return;
            }
            EncodableList wrapped;
            auto output_optional = std::move(output).TakeValue();
            if (output_optional) {
              wrapped.push_back(CustomEncodableValue(std::move(output_optional).value()));
            } else {
              wrapped.push_back(EncodableValue());
            }
            reply(EncodableValue(std::move(wrapped)));
          });
        } catch (const std::exception& exception) {
          reply(WrapError(exception.what()));
        }
      });
    } else {
      channel.SetMessageHandler(nullptr);
    }
  }
}

EncodableValue FlutterPrintApi::WrapError(std::string_view error_message) {
  return EncodableValue(EncodableList{
    EncodableValue(std::string(error_message)),
    EncodableValue("Error"),
    EncodableValue()
  });
}

EncodableValue FlutterPrintApi::WrapError(const FlutterError& error) {
  return EncodableValue(EncodableList{
    EncodableValue(error.code()),
    EncodableValue(error.message()),
    error.details()
  });
}

}  // namespace flutter_print
