name: flutter_print_workspace

environment:
  sdk: ^3.12.0

publish_to: none

dev_dependencies:
  melos: ^7.7.0
  pigeon: ^27.1.0

workspace:
  - flutter_print
  - flutter_print/example
  - flutter_print_platform_interface
  - flutter_print_web
  - flutter_print_windows

melos:
  # Don't generate intellij files
  ide:
    intellij: false

  command:
    # When a dependency in a package is listed it will be replaced with the following versions.
    bootstrap:
      environment:
        sdk: ^3.12.0
        flutter: ">=3.44.0"
      dependencies:
        flutter_print_platform_interface: ^0.1.0
      dev_dependencies:
        # Linter rules (https://pub.dev/packages/flutter_lints)
        flutter_lints: ^6.0.0

  clean:
    hooks:
      # Runs "flutter clean" in all Flutter packages (`--flutter`) with concurrency
      post: melos exec --flutter -c 1 -- "flutter clean"
  
  scripts:
    format:
      description: Format Dart code.
      run: dart format .