name: flutter_print_example
description: "Demonstrates how to use the flutter_print plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

resolution: workspace

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  path_provider: ^2.1.0

  flutter_print: any

  cupertino_icons: ^1.0.8
  web: ^1.0.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/document.pdf
    - assets/image.jpg
    - assets/text.txt
