// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private func doubleEqualsMessages(_ lhs: Double, _ rhs: Double) -> Bool {
  return (lhs.isNaN && rhs.isNaN) || lhs == rhs
}

private func doubleHashMessages(_ value: Double, _ hasher: inout Hasher) {
  if value.isNaN {
    hasher.combine(0x7FF8000000000000)
  } else {
    // Normalize -0.0 to 0.0
    hasher.combine(value == 0 ? 0 : value)
  }
}

func deepEqualsMessages(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
    return true

  case is (Void, Void):
    return true

  case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !deepEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsArray, let rhsArray) as ([Double], [Double]):
    guard lhsArray.count == rhsArray.count else { return false }
    for (index, element) in lhsArray.enumerated() {
      if !doubleEqualsMessages(element, rhsArray[index]) {
        return false
      }
    }
    return true

  case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard lhsDictionary.count == rhsDictionary.count else { return false }
    for (lhsKey, lhsValue) in lhsDictionary {
      var found = false
      for (rhsKey, rhsValue) in rhsDictionary {
        if deepEqualsMessages(lhsKey, rhsKey) {
          if deepEqualsMessages(lhsValue, rhsValue) {
            found = true
            break
          } else {
            return false
          }
        }
      }
      if !found { return false }
    }
    return true

  case (let lhs as Double, let rhs as Double):
    return doubleEqualsMessages(lhs, rhs)

  case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
    return lhsHashable == rhsHashable

  default:
    return false
  }
}

func deepHashMessages(value: Any?, hasher: inout Hasher) {
  let cleanValue = nilOrValue(value) as Any?
  if let cleanValue = cleanValue {
    if let doubleValue = cleanValue as? Double {
      doubleHashMessages(doubleValue, &hasher)
    } else if let valueList = cleanValue as? [Any?] {
      for item in valueList {
        deepHashMessages(value: item, hasher: &hasher)
      }
    } else if let valueList = cleanValue as? [Double] {
      for item in valueList {
        doubleHashMessages(item, &hasher)
      }
    } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
      var result = 0
      for (key, value) in valueDict {
        var entryKeyHasher = Hasher()
        deepHashMessages(value: key, hasher: &entryKeyHasher)
        var entryValueHasher = Hasher()
        deepHashMessages(value: value, hasher: &entryValueHasher)
        result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
      }
      hasher.combine(result)
    } else if let hashableValue = cleanValue as? AnyHashable {
      hasher.combine(hashableValue)
    } else {
      hasher.combine(String(describing: cleanValue))
    }
  } else {
    hasher.combine(0)
  }
}


/// Duplex (double-sided) printing mode.
enum DuplexMode: Int {
  /// Single-sided printing.
  case none = 0
  /// Double-sided, flip along the long edge (portrait binding).
  case longEdge = 1
  /// Double-sided, flip along the short edge (landscape binding).
  case shortEdge = 2
}

/// Identifies a paper size by either a well-known [name] or explicit
/// [width]/[height] dimensions in millimetres.
///
/// When both fields are present, [name] takes priority.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PageSize: Hashable {
  /// Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
  /// `'Letter'`, `'Legal'`. See each platform's documentation for the full
  /// list of accepted names.
  var name: String? = nil
  /// Page width in millimetres. Used when [name] is null or unrecognised.
  var width: Double? = nil
  /// Page height in millimetres. Used when [name] is null or unrecognised.
  var height: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageSize? {
    let name: String? = nilOrValue(pigeonVar_list[0])
    let width: Double? = nilOrValue(pigeonVar_list[1])
    let height: Double? = nilOrValue(pigeonVar_list[2])

    return PageSize(
      name: name,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      name,
      width,
      height,
    ]
  }
  static func == (lhs: PageSize, rhs: PageSize) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.name, rhs.name) && deepEqualsMessages(lhs.width, rhs.width) && deepEqualsMessages(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PageSize")
    deepHashMessages(value: name, hasher: &hasher)
    deepHashMessages(value: width, hasher: &hasher)
    deepHashMessages(value: height, hasher: &hasher)
  }
}

/// Per-side page margins expressed in millimetres.
///
/// **iOS / Windows** — ignored; margins are controlled by the system dialog
///   or the application that handles the print verb.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PageMargins: Hashable {
  /// Top margin in millimetres.
  var top: Double
  /// Bottom margin in millimetres.
  var bottom: Double
  /// Left margin in millimetres.
  var left: Double
  /// Right margin in millimetres.
  var right: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PageMargins? {
    let top = pigeonVar_list[0] as! Double
    let bottom = pigeonVar_list[1] as! Double
    let left = pigeonVar_list[2] as! Double
    let right = pigeonVar_list[3] as! Double

    return PageMargins(
      top: top,
      bottom: bottom,
      left: left,
      right: right
    )
  }
  func toList() -> [Any?] {
    return [
      top,
      bottom,
      left,
      right,
    ]
  }
  static func == (lhs: PageMargins, rhs: PageMargins) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.top, rhs.top) && deepEqualsMessages(lhs.bottom, rhs.bottom) && deepEqualsMessages(lhs.left, rhs.left) && deepEqualsMessages(lhs.right, rhs.right)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PageMargins")
    deepHashMessages(value: top, hasher: &hasher)
    deepHashMessages(value: bottom, hasher: &hasher)
    deepHashMessages(value: left, hasher: &hasher)
    deepHashMessages(value: right, hasher: &hasher)
  }
}

/// Options controlling how a print or print-preview job is submitted.
///
/// Unsupported fields on a given platform are silently ignored.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrintOptions: Hashable {
  /// Technical address of the target printer. Use [PrinterInfo.address] as
  /// the value. When `null` the platform system default printer is used.
  ///
  /// Platform notes:
  /// - **Android** — ignored; the user selects the printer inside the dialog.
  /// - **iOS** — must be a full AirPrint URL (e.g.
  ///   `'ipp://printer.local/ipp/print'`). When provided the job is sent
  ///   directly without showing a dialog.
  /// - **macOS / Windows** — the printer display name (same as
  ///   [PrinterInfo.label] on these platforms).
  /// - **Linux** — the CUPS destination/queue name.
  var printerAddress: String? = nil
  /// Desired output page size.
  ///
  /// Platform support: Android, macOS, Linux (named sizes only), Windows
  /// (passed to the associated application via the shell print verb, actual
  /// support depends on the application).
  var pageSize: PageSize? = nil
  /// Output page margins.
  ///
  /// Ignored on iOS and Windows.
  var margins: PageMargins? = nil
  /// Number of copies to print. Must be ≥ 1.
  ///
  /// Ignored on iOS and Windows (controlled by the system dialog).
  var copies: Int64
  /// Whether to print in landscape orientation.
  var landscape: Bool
  /// Whether to print in colour. Set to `false` for greyscale/monochrome.
  var color: Bool
  /// Duplex (double-sided) printing mode.
  ///
  /// When `null` the platform default is used (typically single-sided).
  /// Ignored on iOS (controlled by the system dialog) and on Windows for
  /// non-image/non-PDF files delegated via ShellExecuteW.
  var duplexMode: DuplexMode? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrintOptions? {
    let printerAddress: String? = nilOrValue(pigeonVar_list[0])
    let pageSize: PageSize? = nilOrValue(pigeonVar_list[1])
    let margins: PageMargins? = nilOrValue(pigeonVar_list[2])
    let copies = pigeonVar_list[3] as! Int64
    let landscape = pigeonVar_list[4] as! Bool
    let color = pigeonVar_list[5] as! Bool
    let duplexMode: DuplexMode? = nilOrValue(pigeonVar_list[6])

    return PrintOptions(
      printerAddress: printerAddress,
      pageSize: pageSize,
      margins: margins,
      copies: copies,
      landscape: landscape,
      color: color,
      duplexMode: duplexMode
    )
  }
  func toList() -> [Any?] {
    return [
      printerAddress,
      pageSize,
      margins,
      copies,
      landscape,
      color,
      duplexMode,
    ]
  }
  static func == (lhs: PrintOptions, rhs: PrintOptions) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.printerAddress, rhs.printerAddress) && deepEqualsMessages(lhs.pageSize, rhs.pageSize) && deepEqualsMessages(lhs.margins, rhs.margins) && deepEqualsMessages(lhs.copies, rhs.copies) && deepEqualsMessages(lhs.landscape, rhs.landscape) && deepEqualsMessages(lhs.color, rhs.color) && deepEqualsMessages(lhs.duplexMode, rhs.duplexMode)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrintOptions")
    deepHashMessages(value: printerAddress, hasher: &hasher)
    deepHashMessages(value: pageSize, hasher: &hasher)
    deepHashMessages(value: margins, hasher: &hasher)
    deepHashMessages(value: copies, hasher: &hasher)
    deepHashMessages(value: landscape, hasher: &hasher)
    deepHashMessages(value: color, hasher: &hasher)
    deepHashMessages(value: duplexMode, hasher: &hasher)
  }
}

/// Capabilities of a specific printer as reported by the host platform.
///
/// Fields may be `null` when the platform does not provide that information.
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrinterCapabilities: Hashable {
  /// Whether the printer can print in colour. `null` if unknown.
  var supportsColor: Bool? = nil
  /// Whether the printer supports duplex (double-sided) printing. `null` if
  /// unknown.
  var supportsDuplex: Bool? = nil
  /// Maximum number of copies the printer accepts in a single job. `null` if
  /// unknown or unlimited.
  var maxCopies: Int64? = nil
  /// Well-known page-size names accepted by this printer (e.g. `'A4'`,
  /// `'Letter'`). Empty when the platform does not report supported sizes.
  var supportedPageSizes: [String?]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterCapabilities? {
    let supportsColor: Bool? = nilOrValue(pigeonVar_list[0])
    let supportsDuplex: Bool? = nilOrValue(pigeonVar_list[1])
    let maxCopies: Int64? = nilOrValue(pigeonVar_list[2])
    let supportedPageSizes = pigeonVar_list[3] as! [String?]

    return PrinterCapabilities(
      supportsColor: supportsColor,
      supportsDuplex: supportsDuplex,
      maxCopies: maxCopies,
      supportedPageSizes: supportedPageSizes
    )
  }
  func toList() -> [Any?] {
    return [
      supportsColor,
      supportsDuplex,
      maxCopies,
      supportedPageSizes,
    ]
  }
  static func == (lhs: PrinterCapabilities, rhs: PrinterCapabilities) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.supportsColor, rhs.supportsColor) && deepEqualsMessages(lhs.supportsDuplex, rhs.supportsDuplex) && deepEqualsMessages(lhs.maxCopies, rhs.maxCopies) && deepEqualsMessages(lhs.supportedPageSizes, rhs.supportedPageSizes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrinterCapabilities")
    deepHashMessages(value: supportsColor, hasher: &hasher)
    deepHashMessages(value: supportsDuplex, hasher: &hasher)
    deepHashMessages(value: maxCopies, hasher: &hasher)
    deepHashMessages(value: supportedPageSizes, hasher: &hasher)
  }
}

/// Describes a single printer returned by [FlutterPrintApi.listPrinters].
///
/// Generated class from Pigeon that represents data sent in messages.
struct PrinterInfo: Hashable {
  /// Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
  var label: String
  /// Platform-specific technical identifier used to address the printer.
  ///
  /// Pass this value as [PrintOptions.printerAddress] to send a job directly
  /// to this printer.
  ///
  /// Platform notes:
  /// - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
  /// - **macOS / Windows** — same as [label]; the display name is the system
  ///   identifier on these platforms.
  /// - **Linux** — CUPS destination/queue name (e.g. `'HP_LaserJet_Pro'`).
  /// - **Android** — not set; the user selects the printer inside the dialog.
  var address: String? = nil
  /// Optional longer description provided by the platform (e.g. the printer
  /// model or location). May be `null`.
  var description: String? = nil
  /// Whether this is the current system-default printer.
  var isDefault: Bool
  /// Capabilities advertised by the printer.
  var capabilities: PrinterCapabilities
  /// Whether the printer is currently online and accepting jobs.
  ///
  /// `true` — printer is idle or processing (online).
  /// `false` — printer is offline or stopped.
  /// `null` — availability cannot be determined on this platform
  ///   (Android and iOS).
  ///
  /// Platform support: macOS, Windows, Linux.
  var isAvailable: Bool? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PrinterInfo? {
    let label = pigeonVar_list[0] as! String
    let address: String? = nilOrValue(pigeonVar_list[1])
    let description: String? = nilOrValue(pigeonVar_list[2])
    let isDefault = pigeonVar_list[3] as! Bool
    let capabilities = pigeonVar_list[4] as! PrinterCapabilities
    let isAvailable: Bool? = nilOrValue(pigeonVar_list[5])

    return PrinterInfo(
      label: label,
      address: address,
      description: description,
      isDefault: isDefault,
      capabilities: capabilities,
      isAvailable: isAvailable
    )
  }
  func toList() -> [Any?] {
    return [
      label,
      address,
      description,
      isDefault,
      capabilities,
      isAvailable,
    ]
  }
  static func == (lhs: PrinterInfo, rhs: PrinterInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return deepEqualsMessages(lhs.label, rhs.label) && deepEqualsMessages(lhs.address, rhs.address) && deepEqualsMessages(lhs.description, rhs.description) && deepEqualsMessages(lhs.isDefault, rhs.isDefault) && deepEqualsMessages(lhs.capabilities, rhs.capabilities) && deepEqualsMessages(lhs.isAvailable, rhs.isAvailable)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PrinterInfo")
    deepHashMessages(value: label, hasher: &hasher)
    deepHashMessages(value: address, hasher: &hasher)
    deepHashMessages(value: description, hasher: &hasher)
    deepHashMessages(value: isDefault, hasher: &hasher)
    deepHashMessages(value: capabilities, hasher: &hasher)
    deepHashMessages(value: isAvailable, hasher: &hasher)
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return DuplexMode(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      return PageSize.fromList(self.readValue() as! [Any?])
    case 131:
      return PageMargins.fromList(self.readValue() as! [Any?])
    case 132:
      return PrintOptions.fromList(self.readValue() as! [Any?])
    case 133:
      return PrinterCapabilities.fromList(self.readValue() as! [Any?])
    case 134:
      return PrinterInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? DuplexMode {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? PageSize {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PageMargins {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PrintOptions {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PrinterCapabilities {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PrinterInfo {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Native print API. All methods are implemented on the host side and invoked
/// from Dart through Pigeon-generated channels.
///
/// Platform support matrix:
///
/// | Method          | Android | iOS | macOS | Windows | Linux | Web |
/// |-----------------|:-------:|:---:|:-----:|:-------:|:-----:|:---:|
/// | [print]         |    ✓    |  ✓  |   ✓   |    ✓    |   ✓   |  ✗  |
/// | [printPreview]  |    ✓*   |  ✓* |   ✓   |    ✓†   |   ✓†  |  ✗  |
/// | [listPrinters]  |    ✗    |  ✗  |   ✓   |    ✓    |   ✓‡  |  ✗  |
/// | [pickPrinter]   |    ✗    |  ✓  |   ✗   |    ✗    |   ✗   |  ✗  |
///
/// \* Android and iOS do not distinguish between a silent print and a preview:
///   both methods open the system print dialog which includes a built-in
///   preview step.
///
/// † On Windows, [printPreview] shows the native Windows print dialog
///   (`PrintDlgEx`). On Linux, [printPreview] opens the file with `xdg-open`.
///
/// ‡ On Linux, printer enumeration requires the CUPS development libraries
///   (`libcups-dev`) to be present at build time. When CUPS is unavailable
///   an empty list is returned.
///
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterPrintApi {
  /// Sends [filePath] directly to the printer described by [options].
  ///
  /// The file must exist and be readable by the process. Supported file
  /// formats depend on the platform and the installed printer drivers (PDF is
  /// universally accepted).
  ///
  /// **Android / iOS** — always opens the system print dialog (which includes
  /// a preview step). The [PrintOptions.printerName] field is ignored on
  /// Android; on iOS it must be a full AirPrint URL to bypass the dialog.
  ///
  /// **macOS** — uses `NSPrintOperation`. For PDF files the job is rendered
  /// page-by-page using PDFKit. Other file types are opened with the default
  /// application instead.
  ///
  /// **Windows** — delegates to `ShellExecuteW` with the `print` verb (or
  /// `printto` when [PrintOptions.printerName] is set). The associated
  /// application handles the actual rendering.
  ///
  /// **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
  /// the `lp` command-line tool when CUPS is not available at build time.
  ///
  /// Throws a [PlatformException] if the file is not found, the file type is
  /// unsupported, or the print subsystem reports an error.
  func print(filePath: String, options: PrintOptions) throws
  /// Opens the native print-preview or print dialog for [filePath].
  ///
  /// **Android / iOS** — identical to [print]: the system print dialog always
  /// includes a preview step on these platforms.
  ///
  /// **macOS** — opens `NSPrintPanel` so the user can review and adjust
  /// settings before printing.
  ///
  /// **Windows** — opens the file in its default application (e.g. a PDF
  /// viewer) using `ShellExecuteW` with the `open` verb. The application's
  /// own print dialog is used for the final print step.
  ///
  /// **Linux** — opens the file with `xdg-open`, delegating preview and
  /// printing to the default document viewer.
  ///
  /// Throws a [PlatformException] if the file is not found.
  func printPreview(filePath: String, options: PrintOptions) throws
  /// Returns all printers currently available on this device.
  ///
  /// **Android / iOS / Web** — always returns an empty list. Android's print
  /// framework only exposes printers inside an active `PrintService` context.
  /// iOS has no public AirPrint enumeration API; use [pickPrinter] instead.
  ///
  /// The I/O is performed on a background thread on all platforms; the
  /// platform UI thread is never blocked.
  func listPrinters(completion: @escaping (Result<[PrinterInfo], Error>) -> Void)
  /// Shows a native AirPrint printer-picker UI and returns the selected
  /// printer, or `null` if the user cancelled.
  ///
  /// **iOS only** — uses `UIPrinterPickerController`. The returned
  /// [PrinterInfo.name] is the full AirPrint URL (e.g.
  /// `ipp://MyPrinter.local./ipp/print`) suitable for use as
  /// [PrintOptions.printerName].
  ///
  /// Returns `null` on all other platforms.
  func pickPrinter(completion: @escaping (Result<PrinterInfo?, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterPrintApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `FlutterPrintApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterPrintApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// Sends [filePath] directly to the printer described by [options].
    ///
    /// The file must exist and be readable by the process. Supported file
    /// formats depend on the platform and the installed printer drivers (PDF is
    /// universally accepted).
    ///
    /// **Android / iOS** — always opens the system print dialog (which includes
    /// a preview step). The [PrintOptions.printerName] field is ignored on
    /// Android; on iOS it must be a full AirPrint URL to bypass the dialog.
    ///
    /// **macOS** — uses `NSPrintOperation`. For PDF files the job is rendered
    /// page-by-page using PDFKit. Other file types are opened with the default
    /// application instead.
    ///
    /// **Windows** — delegates to `ShellExecuteW` with the `print` verb (or
    /// `printto` when [PrintOptions.printerName] is set). The associated
    /// application handles the actual rendering.
    ///
    /// **Linux** — submits the job via CUPS (`cupsPrintFile`). Falls back to
    /// the `lp` command-line tool when CUPS is not available at build time.
    ///
    /// Throws a [PlatformException] if the file is not found, the file type is
    /// unsupported, or the print subsystem reports an error.
    let printChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print.FlutterPrintApi.print\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let optionsArg = args[1] as! PrintOptions
        do {
          try api.print(filePath: filePathArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      printChannel.setMessageHandler(nil)
    }
    /// Opens the native print-preview or print dialog for [filePath].
    ///
    /// **Android / iOS** — identical to [print]: the system print dialog always
    /// includes a preview step on these platforms.
    ///
    /// **macOS** — opens `NSPrintPanel` so the user can review and adjust
    /// settings before printing.
    ///
    /// **Windows** — opens the file in its default application (e.g. a PDF
    /// viewer) using `ShellExecuteW` with the `open` verb. The application's
    /// own print dialog is used for the final print step.
    ///
    /// **Linux** — opens the file with `xdg-open`, delegating preview and
    /// printing to the default document viewer.
    ///
    /// Throws a [PlatformException] if the file is not found.
    let printPreviewChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print.FlutterPrintApi.printPreview\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      printPreviewChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let filePathArg = args[0] as! String
        let optionsArg = args[1] as! PrintOptions
        do {
          try api.printPreview(filePath: filePathArg, options: optionsArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      printPreviewChannel.setMessageHandler(nil)
    }
    /// Returns all printers currently available on this device.
    ///
    /// **Android / iOS / Web** — always returns an empty list. Android's print
    /// framework only exposes printers inside an active `PrintService` context.
    /// iOS has no public AirPrint enumeration API; use [pickPrinter] instead.
    ///
    /// The I/O is performed on a background thread on all platforms; the
    /// platform UI thread is never blocked.
    let listPrintersChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print.FlutterPrintApi.listPrinters\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listPrintersChannel.setMessageHandler { _, reply in
        api.listPrinters { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      listPrintersChannel.setMessageHandler(nil)
    }
    /// Shows a native AirPrint printer-picker UI and returns the selected
    /// printer, or `null` if the user cancelled.
    ///
    /// **iOS only** — uses `UIPrinterPickerController`. The returned
    /// [PrinterInfo.name] is the full AirPrint URL (e.g.
    /// `ipp://MyPrinter.local./ipp/print`) suitable for use as
    /// [PrintOptions.printerName].
    ///
    /// Returns `null` on all other platforms.
    let pickPrinterChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_print.FlutterPrintApi.pickPrinter\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      pickPrinterChannel.setMessageHandler { _, reply in
        api.pickPrinter { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      pickPrinterChannel.setMessageHandler(nil)
    }
  }
}
