// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_MESSAGES_H_
#define PIGEON_MESSAGES_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * FlutterPrintDuplexMode:
 * FLUTTER_PRINT_DUPLEX_MODE_NONE:
 * Single-sided printing.
 * FLUTTER_PRINT_DUPLEX_MODE_LONG_EDGE:
 * Double-sided, flip along the long edge (portrait binding).
 * FLUTTER_PRINT_DUPLEX_MODE_SHORT_EDGE:
 * Double-sided, flip along the short edge (landscape binding).
 *
 * Duplex (double-sided) printing mode.
 */
typedef enum {
  FLUTTER_PRINT_DUPLEX_MODE_NONE = 0,
  FLUTTER_PRINT_DUPLEX_MODE_LONG_EDGE = 1,
  FLUTTER_PRINT_DUPLEX_MODE_SHORT_EDGE = 2
} FlutterPrintDuplexMode;

/**
 * FlutterPrintPageSize:
 *
 * Identifies a paper size by either a well-known [name] or explicit
 * [width]/[height] dimensions in millimetres.
 *
 * When both fields are present, [name] takes priority.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPageSize, flutter_print_page_size, FLUTTER_PRINT, PAGE_SIZE, GObject)

/**
 * flutter_print_page_size_new:
 * name: field in this object.
 * width: field in this object.
 * height: field in this object.
 *
 * Creates a new #PageSize object.
 *
 * Returns: a new #FlutterPrintPageSize
 */
FlutterPrintPageSize* flutter_print_page_size_new(const gchar* name, double* width, double* height);

/**
 * flutter_print_page_size_get_name
 * @object: a #FlutterPrintPageSize.
 *
 * Well-known paper-size identifier. Common values: `'A3'`, `'A4'`, `'A5'`,
 * `'Letter'`, `'Legal'`. See each platform's documentation for the full
 * list of accepted names.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_page_size_get_name(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_get_width
 * @object: a #FlutterPrintPageSize.
 *
 * Page width in millimetres. Used when [name] is null or unrecognised.
 *
 * Returns: the field value.
 */
double* flutter_print_page_size_get_width(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_get_height
 * @object: a #FlutterPrintPageSize.
 *
 * Page height in millimetres. Used when [name] is null or unrecognised.
 *
 * Returns: the field value.
 */
double* flutter_print_page_size_get_height(FlutterPrintPageSize* object);

/**
 * flutter_print_page_size_equals:
 * @a: a #FlutterPrintPageSize.
 * @b: another #FlutterPrintPageSize.
 *
 * Checks if two #FlutterPrintPageSize objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_page_size_equals(FlutterPrintPageSize* a, FlutterPrintPageSize* b);

/**
 * flutter_print_page_size_hash:
 * @object: a #FlutterPrintPageSize.
 *
 * Calculates a hash code for a #FlutterPrintPageSize object.
 *
 * Returns: the hash code.
 */
guint flutter_print_page_size_hash(FlutterPrintPageSize* object);

/**
 * FlutterPrintPageMargins:
 *
 * Per-side page margins expressed in millimetres.
 *
 * **iOS / Windows** — ignored; margins are controlled by the system dialog
 *   or the application that handles the print verb.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPageMargins, flutter_print_page_margins, FLUTTER_PRINT, PAGE_MARGINS, GObject)

/**
 * flutter_print_page_margins_new:
 * top: field in this object.
 * bottom: field in this object.
 * left: field in this object.
 * right: field in this object.
 *
 * Creates a new #PageMargins object.
 *
 * Returns: a new #FlutterPrintPageMargins
 */
FlutterPrintPageMargins* flutter_print_page_margins_new(double top, double bottom, double left, double right);

/**
 * flutter_print_page_margins_get_top
 * @object: a #FlutterPrintPageMargins.
 *
 * Top margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_top(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_get_bottom
 * @object: a #FlutterPrintPageMargins.
 *
 * Bottom margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_bottom(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_get_left
 * @object: a #FlutterPrintPageMargins.
 *
 * Left margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_left(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_get_right
 * @object: a #FlutterPrintPageMargins.
 *
 * Right margin in millimetres.
 *
 * Returns: the field value.
 */
double flutter_print_page_margins_get_right(FlutterPrintPageMargins* object);

/**
 * flutter_print_page_margins_equals:
 * @a: a #FlutterPrintPageMargins.
 * @b: another #FlutterPrintPageMargins.
 *
 * Checks if two #FlutterPrintPageMargins objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_page_margins_equals(FlutterPrintPageMargins* a, FlutterPrintPageMargins* b);

/**
 * flutter_print_page_margins_hash:
 * @object: a #FlutterPrintPageMargins.
 *
 * Calculates a hash code for a #FlutterPrintPageMargins object.
 *
 * Returns: the hash code.
 */
guint flutter_print_page_margins_hash(FlutterPrintPageMargins* object);

/**
 * FlutterPrintPrintOptions:
 *
 * Options controlling how a print or print-preview job is submitted.
 *
 * Unsupported fields on a given platform are silently ignored.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrintOptions, flutter_print_print_options, FLUTTER_PRINT, PRINT_OPTIONS, GObject)

/**
 * flutter_print_print_options_new:
 * printer_address: field in this object.
 * page_size: field in this object.
 * margins: field in this object.
 * copies: field in this object.
 * landscape: field in this object.
 * color: field in this object.
 * duplex_mode: field in this object.
 *
 * Creates a new #PrintOptions object.
 *
 * Returns: a new #FlutterPrintPrintOptions
 */
FlutterPrintPrintOptions* flutter_print_print_options_new(const gchar* printer_address, FlutterPrintPageSize* page_size, FlutterPrintPageMargins* margins, int64_t copies, gboolean landscape, gboolean color, FlutterPrintDuplexMode* duplex_mode);

/**
 * flutter_print_print_options_get_printer_address
 * @object: a #FlutterPrintPrintOptions.
 *
 * Technical address of the target printer. Use [PrinterInfo.address] as
 * the value. When `null` the platform system default printer is used.
 *
 * Platform notes:
 * - **Android** — ignored; the user selects the printer inside the dialog.
 * - **iOS** — must be a full AirPrint URL (e.g.
 *   `'ipp://printer.local/ipp/print'`). When provided the job is sent
 *   directly without showing a dialog.
 * - **macOS / Windows** — the printer display name (same as
 *   [PrinterInfo.label] on these platforms).
 * - **Linux** — the CUPS destination/queue name.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_print_options_get_printer_address(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_page_size
 * @object: a #FlutterPrintPrintOptions.
 *
 * Desired output page size.
 *
 * Platform support: Android, macOS, Linux (named sizes only), Windows
 * (passed to the associated application via the shell print verb, actual
 * support depends on the application).
 *
 * Returns: the field value.
 */
FlutterPrintPageSize* flutter_print_print_options_get_page_size(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_margins
 * @object: a #FlutterPrintPrintOptions.
 *
 * Output page margins.
 *
 * Ignored on iOS and Windows.
 *
 * Returns: the field value.
 */
FlutterPrintPageMargins* flutter_print_print_options_get_margins(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_copies
 * @object: a #FlutterPrintPrintOptions.
 *
 * Number of copies to print. Must be ≥ 1.
 *
 * Ignored on iOS and Windows (controlled by the system dialog).
 *
 * Returns: the field value.
 */
int64_t flutter_print_print_options_get_copies(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_landscape
 * @object: a #FlutterPrintPrintOptions.
 *
 * Whether to print in landscape orientation.
 *
 * Returns: the field value.
 */
gboolean flutter_print_print_options_get_landscape(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_color
 * @object: a #FlutterPrintPrintOptions.
 *
 * Whether to print in colour. Set to `false` for greyscale/monochrome.
 *
 * Returns: the field value.
 */
gboolean flutter_print_print_options_get_color(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_get_duplex_mode
 * @object: a #FlutterPrintPrintOptions.
 *
 * Duplex (double-sided) printing mode.
 *
 * When `null` the platform default is used (typically single-sided).
 * Ignored on iOS (controlled by the system dialog) and on Windows for
 * non-image/non-PDF files delegated via ShellExecuteW.
 *
 * Returns: the field value.
 */
FlutterPrintDuplexMode* flutter_print_print_options_get_duplex_mode(FlutterPrintPrintOptions* object);

/**
 * flutter_print_print_options_equals:
 * @a: a #FlutterPrintPrintOptions.
 * @b: another #FlutterPrintPrintOptions.
 *
 * Checks if two #FlutterPrintPrintOptions objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_print_options_equals(FlutterPrintPrintOptions* a, FlutterPrintPrintOptions* b);

/**
 * flutter_print_print_options_hash:
 * @object: a #FlutterPrintPrintOptions.
 *
 * Calculates a hash code for a #FlutterPrintPrintOptions object.
 *
 * Returns: the hash code.
 */
guint flutter_print_print_options_hash(FlutterPrintPrintOptions* object);

/**
 * FlutterPrintPrinterCapabilities:
 *
 * Capabilities of a specific printer as reported by the host platform.
 *
 * Fields may be `null` when the platform does not provide that information.
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrinterCapabilities, flutter_print_printer_capabilities, FLUTTER_PRINT, PRINTER_CAPABILITIES, GObject)

/**
 * flutter_print_printer_capabilities_new:
 * supports_color: field in this object.
 * supports_duplex: field in this object.
 * max_copies: field in this object.
 * supported_page_sizes: field in this object.
 *
 * Creates a new #PrinterCapabilities object.
 *
 * Returns: a new #FlutterPrintPrinterCapabilities
 */
FlutterPrintPrinterCapabilities* flutter_print_printer_capabilities_new(gboolean* supports_color, gboolean* supports_duplex, int64_t* max_copies, FlValue* supported_page_sizes);

/**
 * flutter_print_printer_capabilities_get_supports_color
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Whether the printer can print in colour. `null` if unknown.
 *
 * Returns: the field value.
 */
gboolean* flutter_print_printer_capabilities_get_supports_color(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_get_supports_duplex
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Whether the printer supports duplex (double-sided) printing. `null` if
 * unknown.
 *
 * Returns: the field value.
 */
gboolean* flutter_print_printer_capabilities_get_supports_duplex(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_get_max_copies
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Maximum number of copies the printer accepts in a single job. `null` if
 * unknown or unlimited.
 *
 * Returns: the field value.
 */
int64_t* flutter_print_printer_capabilities_get_max_copies(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_get_supported_page_sizes
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Well-known page-size names accepted by this printer (e.g. `'A4'`,
 * `'Letter'`). Empty when the platform does not report supported sizes.
 *
 * Returns: the field value.
 */
FlValue* flutter_print_printer_capabilities_get_supported_page_sizes(FlutterPrintPrinterCapabilities* object);

/**
 * flutter_print_printer_capabilities_equals:
 * @a: a #FlutterPrintPrinterCapabilities.
 * @b: another #FlutterPrintPrinterCapabilities.
 *
 * Checks if two #FlutterPrintPrinterCapabilities objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_printer_capabilities_equals(FlutterPrintPrinterCapabilities* a, FlutterPrintPrinterCapabilities* b);

/**
 * flutter_print_printer_capabilities_hash:
 * @object: a #FlutterPrintPrinterCapabilities.
 *
 * Calculates a hash code for a #FlutterPrintPrinterCapabilities object.
 *
 * Returns: the hash code.
 */
guint flutter_print_printer_capabilities_hash(FlutterPrintPrinterCapabilities* object);

/**
 * FlutterPrintPrinterInfo:
 *
 * Describes a single printer returned by [FlutterPrintApi.listPrinters].
 */

G_DECLARE_FINAL_TYPE(FlutterPrintPrinterInfo, flutter_print_printer_info, FLUTTER_PRINT, PRINTER_INFO, GObject)

/**
 * flutter_print_printer_info_new:
 * label: field in this object.
 * address: field in this object.
 * description: field in this object.
 * is_default: field in this object.
 * capabilities: field in this object.
 *
 * Creates a new #PrinterInfo object.
 *
 * Returns: a new #FlutterPrintPrinterInfo
 */
FlutterPrintPrinterInfo* flutter_print_printer_info_new(const gchar* label, const gchar* address, const gchar* description, gboolean is_default, FlutterPrintPrinterCapabilities* capabilities);

/**
 * flutter_print_printer_info_get_label
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Human-readable display name shown to the user (e.g. `'HP LaserJet Pro'`).
 *
 * Returns: the field value.
 */
const gchar* flutter_print_printer_info_get_label(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_address
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Platform-specific technical identifier used to address the printer.
 *
 * Pass this value as [PrintOptions.printerAddress] to send a job directly
 * to this printer.
 *
 * Platform notes:
 * - **iOS** — full AirPrint URL (e.g. `'ipp://printer.local/ipp/print'`).
 * - **macOS / Windows** — same as [label]; the display name is the system
 *   identifier on these platforms.
 * - **Linux** — CUPS destination/queue name (e.g. `'HP_LaserJet_Pro'`).
 * - **Android** — not set; the user selects the printer inside the dialog.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_printer_info_get_address(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_description
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Optional longer description provided by the platform (e.g. the printer
 * model or location). May be `null`.
 *
 * Returns: the field value.
 */
const gchar* flutter_print_printer_info_get_description(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_is_default
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Whether this is the current system-default printer.
 *
 * Returns: the field value.
 */
gboolean flutter_print_printer_info_get_is_default(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_get_capabilities
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Capabilities advertised by the printer.
 *
 * Returns: the field value.
 */
FlutterPrintPrinterCapabilities* flutter_print_printer_info_get_capabilities(FlutterPrintPrinterInfo* object);

/**
 * flutter_print_printer_info_equals:
 * @a: a #FlutterPrintPrinterInfo.
 * @b: another #FlutterPrintPrinterInfo.
 *
 * Checks if two #FlutterPrintPrinterInfo objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean flutter_print_printer_info_equals(FlutterPrintPrinterInfo* a, FlutterPrintPrinterInfo* b);

/**
 * flutter_print_printer_info_hash:
 * @object: a #FlutterPrintPrinterInfo.
 *
 * Calculates a hash code for a #FlutterPrintPrinterInfo object.
 *
 * Returns: the hash code.
 */
guint flutter_print_printer_info_hash(FlutterPrintPrinterInfo* object);

G_DECLARE_FINAL_TYPE(FlutterPrintMessageCodec, flutter_print_message_codec, FLUTTER_PRINT, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int flutter_print_duplex_mode_type_id;
extern const int flutter_print_page_size_type_id;
extern const int flutter_print_page_margins_type_id;
extern const int flutter_print_print_options_type_id;
extern const int flutter_print_printer_capabilities_type_id;
extern const int flutter_print_printer_info_type_id;

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApi, flutter_print_flutter_print_api, FLUTTER_PRINT, FLUTTER_PRINT_API, GObject)

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiResponseHandle, flutter_print_flutter_print_api_response_handle, FLUTTER_PRINT, FLUTTER_PRINT_API_RESPONSE_HANDLE, GObject)

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiPrintResponse, flutter_print_flutter_print_api_print_response, FLUTTER_PRINT, FLUTTER_PRINT_API_PRINT_RESPONSE, GObject)

/**
 * flutter_print_flutter_print_api_print_response_new:
 *
 * Creates a new response to FlutterPrintApi.print.
 *
 * Returns: a new #FlutterPrintFlutterPrintApiPrintResponse
 */
FlutterPrintFlutterPrintApiPrintResponse* flutter_print_flutter_print_api_print_response_new();

/**
 * flutter_print_flutter_print_api_print_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to FlutterPrintApi.print.
 *
 * Returns: a new #FlutterPrintFlutterPrintApiPrintResponse
 */
FlutterPrintFlutterPrintApiPrintResponse* flutter_print_flutter_print_api_print_response_new_error(const gchar* code, const gchar* message, FlValue* details);

G_DECLARE_FINAL_TYPE(FlutterPrintFlutterPrintApiPrintPreviewResponse, flutter_print_flutter_print_api_print_preview_response, FLUTTER_PRINT, FLUTTER_PRINT_API_PRINT_PREVIEW_RESPONSE, GObject)

/**
 * flutter_print_flutter_print_api_print_preview_response_new:
 *
 * Creates a new response to FlutterPrintApi.printPreview.
 *
 * Returns: a new #FlutterPrintFlutterPrintApiPrintPreviewResponse
 */
FlutterPrintFlutterPrintApiPrintPreviewResponse* flutter_print_flutter_print_api_print_preview_response_new();

/**
 * flutter_print_flutter_print_api_print_preview_response_new_error:
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Creates a new error response to FlutterPrintApi.printPreview.
 *
 * Returns: a new #FlutterPrintFlutterPrintApiPrintPreviewResponse
 */
FlutterPrintFlutterPrintApiPrintPreviewResponse* flutter_print_flutter_print_api_print_preview_response_new_error(const gchar* code, const gchar* message, FlValue* details);

/**
 * FlutterPrintFlutterPrintApiVTable:
 *
 * Table of functions exposed by FlutterPrintApi to be implemented by the API provider.
 */
typedef struct {
  FlutterPrintFlutterPrintApiPrintResponse* (*print)(const gchar* file_path, FlutterPrintPrintOptions* options, gpointer user_data);
  FlutterPrintFlutterPrintApiPrintPreviewResponse* (*print_preview)(const gchar* file_path, FlutterPrintPrintOptions* options, gpointer user_data);
  void (*list_printers)(FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
  void (*pick_printer)(FlutterPrintFlutterPrintApiResponseHandle* response_handle, gpointer user_data);
} FlutterPrintFlutterPrintApiVTable;

/**
 * flutter_print_flutter_print_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the FlutterPrintApi API.
 */
void flutter_print_flutter_print_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const FlutterPrintFlutterPrintApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * flutter_print_flutter_print_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the FlutterPrintApi API.
 */
void flutter_print_flutter_print_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * flutter_print_flutter_print_api_respond_list_printers:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FlutterPrintApi.listPrinters. 
 */
void flutter_print_flutter_print_api_respond_list_printers(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlValue* return_value);

/**
 * flutter_print_flutter_print_api_respond_error_list_printers:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.listPrinters. 
 */
void flutter_print_flutter_print_api_respond_error_list_printers(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * flutter_print_flutter_print_api_respond_pick_printer:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to FlutterPrintApi.pickPrinter. 
 */
void flutter_print_flutter_print_api_respond_pick_printer(FlutterPrintFlutterPrintApiResponseHandle* response_handle, FlutterPrintPrinterInfo* return_value);

/**
 * flutter_print_flutter_print_api_respond_error_pick_printer:
 * @response_handle: a #FlutterPrintFlutterPrintApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to FlutterPrintApi.pickPrinter. 
 */
void flutter_print_flutter_print_api_respond_error_pick_printer(FlutterPrintFlutterPrintApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_MESSAGES_H_
